name: learn-github-actions

on: workflow_dispatch
jobs:
  deploy-AAB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - working-directory: ./MyApp
        run: |
          npm install
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec fastlane android deploy_production bundle:true
